### ISSUE TITLE
AdminLTE Error while binding via database driven from mysql

### ISSUE THREAD

**Issue by sathishpsy89** [almasaeed2010/AdminLTE#1744]
Hi,
 
  I am happy that i can fetch data from database and load in AdminLTE ( version 2.3.2 & 2.4.0)menu. 
  but i got error while collapsing the menu by clicking the toggle button.
  
![menuerror](https://user-images.githubusercontent.com/10058088/33229638-3def241e-d1f8-11e7-8ae7-fe33f57ce897.png)

![menuerror2](https://user-images.githubusercontent.com/10058088/33229640-680b8c1a-d1f8-11e7-94e8-9164810026d4.png)

**Comment by almasaeed2010** [comment]
Please make sure that your HTML markup is correct.

Thanks!

**Comment by sathishpsy89** [comment]
Hi,
  I had tried out in many scenarios and i have attached the code where i implemented,kindly correct the code if there is any wrong in my code.

Master1.Master [Master Page in asp.net]:
--------------------------------------------------------
<%@ Master Language="C#" AutoEventWireup="true" CodeBehind="Master1.master.cs" Inherits="DML_EHRM.Master.Master1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" />

    
    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css" />

    
    <link href="font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />

    
    <link href="ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" />

    
    <link href="Content/ej/web/default-theme/ej.web.all.min.css" rel="stylesheet" />
    <link href="Content/ej/web/ej.widgets.core.min.css" rel="stylesheet" />
    <script src='<%= Page.ResolveClientUrl("~/Scripts/jquery-1.10.2.min.js")%>' type="text/javascript"></script>
    <script src='<%= Page.ResolveClientUrl("~/Scripts/jsrender.min.js")%>' type="text/javascript"></script>
    <script src='<%= Page.ResolveClientUrl("~/Scripts/ej/web/ej.web.all.min.js")%>' type="text/javascript"></script>
    <script src='<%= Page.ResolveClientUrl("~/Scripts/ej/common/ej.webform.min.js")%>' type="text/javascript"></script>
    <script src='<%= Page.ResolveClientUrl("~/Scripts/jquery.validate.min.js")%>' type="text/javascript"></script>

    
    <link href="dist/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="dist/css/skins/_all-skins.min.css" rel="stylesheet" />

    
    <link href="dist/css/wiremonkey.css" rel="stylesheet" />

    <script type="text/javascript">
       

       
    </script>

</head>
<body class="hold-transition skin-blue sidebar-mini">
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <div class="wrapper">
            <header class="main-header">
                
                <a href="" class="logo">
                    <span class="logo-mini">
                        <img src="" /></span>
                    
                    <span class="logo-lg" id="spanAppName"><b></b></span>
                </a>
                
                <nav class="navbar navbar-static-top">
                    
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            
                            
                            
                            
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <img src="" class="user-image" />
                                    <span class="hidden-xs"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    
                                    <li class="user-header">
                                        <img src="" class="img-circle" />
                                        <p>
                                            <small></small>
                                        </p>
                                    </li>
                                    

                                    
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="#" class="btn btn-default btn-flat">Profile</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="#" class="btn btn-default btn-flat">Sign out</a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            

                        </ul>
                    </div>
                </nav>
                  
            </header>
            
            <aside class="main-sidebar">
                
                <section class="sidebar">
                    
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="" class="img-circle" />
                        </div>
                        <div class="pull-left info">
                            <p></p>
                            <a href="#"><i class="fa fa-circle text-success"></i>Online</a>
                        </div>
                    </div>
                        
                        
                        
                        
                        <ul class="sidebar-menu">
                            <li><a href="#">DD0</a>
                                <ul class="treeview-menu">
                                    <li><a href="Master/DD1.aspx">DD1</a></li>
                                </ul>
                            </li>                           
                        </ul>    

                          <asp:Repeater ID="rptMenu" runat="server" OnItemDataBound="rptMenu_OnItemBound">
                              <ItemTemplate>
                               <ul class="sidebar-menu">
                                  <li class="treeview">
                                       <a href='<%#Eval("Menu_Url") %>'><i class='<%#Eval("Menu_Icon") %>'></i><%#Eval("Menu_Name") %></a>
                                       <ul class="treeview-menu">
                                          <asp:Repeater ID="rptChildMenu" runat="server">
                                              <ItemTemplate>
                                                  <li><a href="Master/DD1.aspx"><i class='<%#Eval("Menu_Icon") %>'></i><%#Eval("Menu_Name") %></a></li>
                                              </ItemTemplate>
                                          </asp:Repeater>
                                      </ul>
                                  </li>
                                </ul>                                 
                              </ItemTemplate>
                           </asp:Repeater>**   
                </section>
              
                
            </aside>
            
            <div class="content-wrapper" style="background-color: #ffe8e8">
                
                <section class="content-header">
                    <h1>Year Master  
                        <small>2017 - 2018</small>
                    </h1>
                </section>

                
                <section class="content">
                    <asp:ContentPlaceHolder ID="MainContentPlaceHolder1" runat="server">
                    </asp:ContentPlaceHolder>
                </section>
                
            </div>
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 1.0.0
                </div>
                <strong>Copyright &copy; 2017-2018 <a href="http://drmiltons.com">Dr.Miltons Labarotories</a>.</strong> All rights reserved.
            </footer>

            <div class="control-sidebar-bg"></div>
        </div>
           
        <script src="<%= ResolveUrl("~/Scripts/jquery-1.10.2.min.js") %>" type="text/javascript"></script>
        <script src="<%= ResolveUrl("~/bootstrap/js/bootstrap.min.js") %>" type="text/javascript"></script>
        <script src="<%= ResolveUrl("~/bootstrap/js/bootstrap.min.js") %>" type="text/javascript"></script>
        <script src="<%= ResolveUrl("~/dist/js/app.min.js") %>" type="text/javascript"></script>
        <script src="<%= ResolveUrl("~/dist/js/demo.js") %>" type="text/javascript"></script>
    </form>
</body>
</html>
-------------------End Of Html Tag

Master1.Master.cs page 
------------------------------------------------
protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                this.BindMenu();              

            }
        }

        protected void rptMenu_OnItemBound(object sender, RepeaterItemEventArgs e)
        {
            if (e.Item.ItemType == ListItemType.Item || e.Item.ItemType == ListItemType.AlternatingItem)
            {
                Repeater rptSubMenu = e.Item.FindControl("rptChildMenu") as Repeater;
                rptSubMenu.DataSource = UDF.FillDataTable("SELECT Parent_Child_ID,Menu_Name,Menu_Url,Menu_Icon FROM dml_menu_setting WHERE Parent_Child_ID =" + ((System.Data.DataRowView)(e.Item.DataItem)).Row[0], false);
                rptSubMenu.DataBind();
            }
        }

        private void BindMenu()
        {
            this.rptMenu.DataSource = UDF.FillDataTable("SELECT Menu_ID, Parent_Child_ID, Menu_Name, Menu_Description, Menu_Url,Menu_Icon FROM dml_menu_setting WHERE Menu_Status=1 AND Parent_Child_Id = 0", false);
            this.rptMenu.DataBind();
        }

**Comment by sathishpsy89** [comment]
Is there any update regarding this issue

**Comment by REJack** [comment]
1. learn to use Github, use a real [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/) for better code display, it's way to hard to check these lines. 

2. Change your aspRepeater#rptMenu ItemTemplate to this 
```
<ul class="sidebar-menu">
  <li class="treeview">
    <a href='<%#Eval("Menu_Url") %>'>
      <i class='<%#Eval("Menu_Icon") %>'></i>
      <span><%#Eval("Menu_Name") %></span>
      <ul class="treeview-menu">
        <asp:Repeater ID="rptChildMenu" runat="server">
          <ItemTemplate>
            <li><a href="Master/DD1.aspx"><i class='<%#Eval("Menu_Icon") %>'></i><%#Eval("Menu_Name") %></a></li>
          </ItemTemplate>
        </asp:Repeater>
      </ul>
    </a>
  </li>
</ul>                                 
```
You missed the `span` around your Menu_Name.

This is still not perfect but should work, 
in my opinion you should not repeat to much the `<ul class="sidebar-menu">` I would place the repeat without the `ul` and try also to add only `class="treeview"` if rptChildMenu is filled & if rptChildMenu is not filled don't display `class="treeview"` otherwise you can't use the link.

**Comment by sathishpsy89** [comment]
Hi Alma Saeed,
      It's working
