### ISSUE TITLE
tooltip problem

### ISSUE THREAD

**Issue by micegames** [almasaeed2010/AdminLTE#210]
I don't know why but data-toggle="tooltip" don't work as excepted. Instead of the callout a simple black text are displayed aligned to the left of the screen.

**Comment by almasaeed2010** [comment]
I saw the problem a while back and I thought I have fixed it. Apparently, I didn't. If I am not mistaken, the issue only appears in the dashboard page but everything works fine in other pages. You can check the widgets page and you'll notice that it is working fine. We are currently very busy building AdminLTE 2.0 and hopefully the next release will have that issue resolved. Thanks for the contribution.

**Comment by almasaeed2010** [comment]
I think the problem is related to a conflict with other scripts on the page because it works everywhere else. If anyone find a solution, please let me know! Thanks.

**Comment by kressly** [comment]
It is working for me. Where is it not working ? Can u give us a url ?

**Comment by almasaeed2010** [comment]
almsaeedstudio.com/AdminLTE
When you hover over the minus sign in the map box (at the top box-tools) in the Dashboard page, you get the value of the tooltip title in the left sidebar. Like this:
![screen shot 2015-01-18 at 4 49 39 pm](https://cloud.githubusercontent.com/assets/1512664/5794207/08983f4a-9f32-11e4-82fb-44a4cd2a709f.png)

**Comment by kressly** [comment]
I just went to http://almsaeedstudio.com/AdminLTE/ and i am still not seeing the problem 
![1](https://cloud.githubusercontent.com/assets/925132/5794778/1443e81a-9f75-11e4-87ed-daf578f40ef7.png)
![2](https://cloud.githubusercontent.com/assets/925132/5794779/144976fe-9f75-11e4-895b-1fc7dbc08a9a.png)

**Comment by almasaeed2010** [comment]
I finally discovered the problem. There is a conflict between Bootstrap.js and jQueryUI.js. I don't know how to solve this without removing jQuery UI.

**Comment by kressly** [comment]
I am using bootstrap with jqueryui and prototype js and scriptaculous and protoplasm it is working perfectly. All i did was to 1) Put jquery in noconflict mod and then i opened the Bootrap.js file and added the rest of the jquery no conflict code like at the top, very begining of Bootstrap i added this
```
 jQuery( document ).ready(function( $ ) {
// Code that uses jQuery's $ can follow here.
///////////////////////////////////////////////////////////////////////////////
```
And at the very end i added this
```
///////////////////////////////////////////////////////////////////////////////

});
```

And since i am using jquery in noconflict mode, i put every single jquery code always between another 
```
 jQuery( document ).ready(function( $ ) {
// Code that uses jQuery's $ can follow here.
///////////////////////////////////////////////////////////////////////////////
```
And 
```
///////////////////////////////////////////////////////////////////////////////

});
```
Every Jquery code whether jqueryui, Bootstrap, jquery itself that i use i put them between those line.

I wish i can understand the problem you are facing, because i still don't see it clearing in the image
But you can check out a demo of how i am using most of those library at 

http://usefaith.voiedusucces.net/

**Comment by lenamtl** [comment]
I remember having an issue because I was trying to add 2 classes to data-toggle=" " 
and it's not possible (only one class can be use).
Let say you want to add a tootltip on toggle button
original code
```
<a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
```
So I ended up with
```
<a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button" data-tooltip="tooltip" title="Toggle">
```

I remember that another user got tooltip compatibility issue between Bootstrap & Jquery UI.

**Comment by kressly** [comment]
I forgot to mention that i placed also apps.js in noConflict mod up to a point in the script. There are some place where i could not

**Comment by lenamtl** [comment]
I don't know, I'm not using noConflict, I don't need this I'm using jQuery only.

**Comment by micegames** [comment]
Yeah, the problem is a conflict with jQuery-UI that I don't use :-)
Incredible how active is this community and work you made! Many many many thanks!

**Comment by kressly** [comment]
:+1:

**Comment by xMazlan** [comment]
**SOLVED**
demo.js required
`<script src="../dist/js/demo.js"></script>`
